blog/urls.py
from . import views
from django.urls import path


urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>', views.PostDetails.as_view(), name='post_detail'),
    path('like/<slug:slug>', views.PostLike.as_view(), name='post_like')
]

codestar/urls.py
from django.contrib import admin
from django.urls import path, include
from blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blog.urls'), name='blog_url'),
    path('accounts/', include('allauth.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField

# Create your models here.

STATUS = ((0, 'Draft'), (1, 'Published'))


class Posts(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(User, related_name="blog_likes", blank=True)
    
    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()


class Comment(models.Model):
    name = models.CharField(max_length=200, unique=True)
    email = models.EmailField(unique=True)
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    post = models.ForeignKey(Posts, on_delete=models.CASCADE, related_name='comment')

    class Meta:
        ordering = ['created_on']
    
    def __str__(self):
        return f"Comments {self.body} by {self.name}"

        

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse
from django.views import generic, View
from .models import Posts, Comment
from .forms import CommentForm
from django.http import HttpResponseRedirect
from django.contrib import messages

# Create your views here.


def get_base(request):
    return render(request, 'index.html')


class PostList(generic.ListView):
    model = Posts
    queryset = Posts.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'
    paginate_by = 5


class PostDetails(View):
    def get(self, request, slug, *args, **kwargs):
        query_post = Posts.objects.filter(status=1)
        post = get_object_or_404(query_post, slug=slug)
        comments = post.comment.filter(approved=True).order_by('created_on')
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True
        return render(
            request,
            'post_detail.html',
            {
                'post': post,
                'comments': comments,
                'commented': False,
                'liked': liked,
                'comment_form': CommentForm()
            },
        )

    def post(self, request, slug, *args, **kwargs):
        messages.add_message(request, messages.INFO, request.user.username + "  added the comment successfully")
        query_post = Posts.objects.filter(status=1)
        post = get_object_or_404(query_post, slug=slug)
        comment_all = post.comment.filter(approved=True).order_by('created_on')
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True
        form_data = CommentForm(data=request.POST)
        if form_data.is_valid():
            form_data.instance.email = request.user.email
            form_data.instance.name = request.user.username
            comment = form_data.save(commit=False)
            comment.post = post
            comment.save()                    
        else:
            form_data = CommentForm()
            print(" CommentForm") 
            
        return render(
                request, 
                'post_detail.html', 
                {
                    'liked': liked,
                    'comments': comment_all,
                    'commented': True,
                    'post': post,
                    'comment_form': CommentForm()
                }
            )


class PostLike(View):
    def post(self, request, slug):
        # posts = Posts.objects.filter(status=1)
        post = get_object_or_404(Posts, slug=slug)
        if post.likes.filter(id=self.request.user.id).exists():
            post.likes.remove(self.request.user)
        else:
            post.likes.add(self.request.user)

        return HttpResponseRedirect(reverse("post_detail", args=[slug]))

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="h-100">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href="CLOUDINARY_URL=cloudinary://454417718783186:aKJHNDLwazrlaqZ7wvNdXRRCHQI@drulpekag" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>CodeStar Blog</title>
</head>

<body class="d-flex flex-column h-100 main-bg">

    <!----------- navigation  -------------------->
    <nav class="navbar navbar-expand-lg navbar-light bg-white">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"><span>c<span class="red-o">o</span>de<span
                        class="thin">|star</span></span></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" href="#" aria-current="page">Home</a>
                    </li>

                    <li class="nav-item">
                        {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'account_logout' %}">LogOut</a>
                        {% else %}
                        <a class="nav-link" href="{% url 'account_login' %}">LogIn</a>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_signup' %}">Register</a>
                    </li>
                    {% endif %}
                    </li>
                </ul>
                <span class="navbar-text text-muted">adventures of a software developer</span>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                {% for message in messages %}
                <div class="alert {{message.tags }} alert-dismissible fade show" role="alert" id="msg">
                    {{ message | safe }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!----------- main content  ------------------>
    <main class="main-bg flex-shrink-0">
        {% block content %}
        {% endblock content %}

    </main>
    <!-------------  Footer  --------------------->
    <footer class="footer dark-bg mt-auto py-3 ">
        <p class="m-0 text-center text-white">Made by Code Instituters</p>
        <p class="m-0 text-center text-white">Follow us: <i class="fab fa-facebook-square ms-3"></i>
            <i class="fab fa-twitter-square ms-3"></i>
            <i class="fab fa-instagram-square ms-3"></i>
            <i class="fab fa-youtube-square ms-3"></i></p>
    </footer>
    <script>
        setTimeout(function(){
            let msg = document.getElementById('msg')
            let bsAlert = new bootstrap.Alert(msg)
            bsAlert.close();
        }, 3000);
    </script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}

<div class="container-fluid">
    <div class="row">
        <!-- blog list -->
        <div class="col-12 mt-3">
            <div class="row">
                {% for post in posts_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if 'placeholder' in post.featured_image.url %}
                                <img src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg"
                                    class="card-img-top" alt="tite-image">
                                {% else %}
                                <img src="{{post.featured_image.url}}" class="card-img-top" alt="">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Author: {{post.Author}}</p>
                                </div>
                            </div>
                            <a href="{% url 'post_detail' post.slug %}" class="post-link">
                                <h2 class="card-title">{{post.title}}</h2>
                                <p class="card-text">{{post.excerpt}}</p>
                            </a>
                            <hr>
                            <p class="card-textt text-muted h6">{{post.created_on}} <i class="far fa-heart"></i>
                                {{post.number_of_likes}}
                            </p>
                        </div>
                    </div>
                </div>
            {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% if is_paginated %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}
</div>
{% endblock %}

templates/post_detail.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}
<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <h1 class="post-title">{{post.title}}</h1>
                <p class="post-subtitle">{{post.author}} | {{post.created_on}}</p>
            </div>
            <div class="d-none d-md-block col-md-6 masthead-image">
                {% if "placeholder" in post.featured_image.url %}
                <img src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg" width="100%">
                {% else %}
                <img src="{{post.featured_image.url}}" width="100%">
                {% endif %}
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col card mb-4 mt-3 left top">
            <div class="card-body">
                <p class="card-text">{{post.content|safe}}</p>
                <div class="row">
                    <div class="col-1">
                        <strong>
                            {% if user.is_authenticated %}
                            <form class="d-inline" method="POST" action="{% url 'post_like' post.slug  %}">
                                {% csrf_token %}
                                {% if liked %}
                                <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i
                                        class="fas fa-heart"></i></button>
                                {% else %}
                                <button type="submit" name="blogpost_id" value="{{post.slug}}" class="btn-like"><i
                                        class="far fa-heart"></i></button>
                                {% endif %}

                            </form>
                            {% else %}
                            <span class="text-secondary"><i class="far fa-heart"></i></span>
                            {% endif %}
                            <span class="text-secondary">{{ post.number_of_likes }}</span>
                        </strong>
                    </div>
                    <div class="col-1">
                        {% with comments.count as total_comments %}
                        <strong class="text-secondary"><i class="far fa-comments"></i>
                            <!-- Our total_comments variable goes before the closing strong tag -->
                            {{total_comments}}
                        </strong>
                        {% endwith %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <hr>
        </div>
    </div>
    <div class="row">
        <div class="col card mb-4 mt-3">
            <h3>Comments:</h3>
            <div class="car-body">
                {% for comment in comments %}
                <div class="comments">
                    <p>
                        {{comment.name}}
                        <span class="text-muted">{{comment.created_on}}</span>
                        wrote:
                    </p>
                    {{comment.body}}
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4 card mb-4  mt-3 ">
            {% if commented %}
            <div class="row">
                <div class="col-md-8 offset-md-2">
                    {% for message in messages %}
                    <div class="alert {{message.tags}} alert-dismissible fade show" role="alert">
                        {{message | safe}}
                      </div>
                    {% endfor %}
                </div>
            </div>
            {% endif %}
            <div class="card-body">
                {% if commented %}
                <div class="alert alert-success">
                    Your comment is waiting approval
                </div>
                {% else %}
                {% if user.is_authenticated %}
                <h3>Leave a comment:</h3>
                <p>Posting as : {{user.username}}</p>
                <form method="POST" style="margin-top: 1.3em;">
                    {{comment_form | crispy}}
                    {% csrf_token %}
                    <button type="submit" class="btn btn-signup btn-lg">Submit</button>
                </form>
                {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}